Let's try some stuff

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -18,49 +18,23 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        settings:
-#          - host: macos-latest
-#            target: x86_64-apple-darwin
-#            build: |
-#              yarn build
-#              strip -x *.node
-          - host: macos-latest
-            target: aarch64-apple-darwin
-            build: |
-              yarn build --target aarch64-apple-darwin
-              strip -x *.node
-#          - host: windows-latest
-#            build: yarn build
-#            target: x86_64-pc-windows-msvc
-          - host: ubuntu-latest
-            target: x86_64-unknown-linux-gnu
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
-            output_suffix: linux-x64-gnu
-            build: |-
-              set -e &&
-              yarn build --target x86_64-unknown-linux-gnu &&
-              strip *.node
-    name: stable - ${{ matrix.settings.target }} - node@18
-    runs-on: ${{ matrix.settings.host }}
+  publish:
+    name: Publish
+    env:
+      TARGET: x86_64-unknown-linux-gnu
+      HOST: ubuntu-latest
+      DOCKER_IMAGE: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
+    runs-on: ${{ env.HOST }}
     steps:
       - uses: actions/checkout@v3
       - name: Setup node
         uses: actions/setup-node@v3
-        if: ${{ !matrix.settings.docker }}
         with:
           node-version: 18
           check-latest: true
           cache: yarn
-      - name: Install
-        uses: dtolnay/rust-toolchain@stable
-        if: ${{ !matrix.settings.docker }}
-        with:
-          toolchain: stable
-          targets: ${{ matrix.settings.target }}
+      - name: Install JS dependencies
+        run: yarn install
       - name: Cache cargo
         uses: actions/cache@v3
         with:
@@ -70,74 +44,18 @@ jobs:
             ~/.cargo/git/db/
             .cargo-cache
             target/
-          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
-      - uses: goto-bus-stop/setup-zig@v2
-        if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' }}
-        with:
-          version: 0.10.1
-      - name: Setup toolchain
-        run: ${{ matrix.settings.setup }}
-        if: ${{ matrix.settings.setup }}
-        shell: bash
-      - name: Setup node x86
-        if: matrix.settings.target == 'i686-pc-windows-msvc'
-        run: yarn config set supportedArchitectures.cpu "ia32"
-        shell: bash
-      - name: Install dependencies
-        run: yarn install
-      - name: Setup node x86
-        uses: actions/setup-node@v3
-        if: matrix.settings.target == 'i686-pc-windows-msvc'
-        with:
-          node-version: 18
-          check-latest: true
-          cache: yarn
-          architecture: x86
+          key: publish-${{ env.TARGET }}-cargo-${{ env.HOST }}
       - name: Build in docker
         uses: addnab/docker-run-action@v3
-        if: ${{ matrix.settings.docker }}
         with:
-          image: ${{ matrix.settings.docker }}
+          image: ${{ env.DOCKER_IMAGE }}
           options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build"
-          run: ${{ matrix.settings.build }}
-      - name: Build
-        run: ${{ matrix.settings.build }}
-        if: ${{ !matrix.settings.docker }}
-        shell: bash
-      - name: Artifact name
-        run: echo "ARTIFACT_NAME=$(ls ${{ env.APP_NAME }}.*.node)" >> $GITHUB_ENV
-        shell: bash
-      - name: List
-        run: ls -al
-        shell: bash
-      - name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.ARTIFACT_NAME }}
-          path: ${{ env.APP_NAME }}.*.node
-          if-no-files-found: error
-  publish:
-    name: Publish
-    runs-on: ubuntu-latest
-    needs:
-      - build
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-          check-latest: true
-          cache: yarn
-      - name: Install deps
-        run: yarn install
-      - name: Download all artifacts
-        uses: actions/download-artifact@v3
-        with:
-          path: .
-      - name: Unzip files
-        shell: bash
-        run: unzip *.node && ls -al
+          run: |-
+            set -e &&
+            yarn build --target ${{ env.TARGET }} &&
+            strip *.node
+      - name: List files
+        run: ls -al && ls -al lib
       - name: PR or Publish
         id: changesets
         uses: changesets/action@v1
@@ -147,3 +65,104 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+
+#  build:
+#    if: false
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        settings:
+##          - host: macos-latest
+##            target: x86_64-apple-darwin
+##            build: |
+##              yarn build
+##              strip -x *.node
+#          - host: macos-latest
+#            target: aarch64-apple-darwin
+#            build: |
+#              yarn build --target aarch64-apple-darwin
+#              strip -x *.node
+##          - host: windows-latest
+##            build: yarn build
+##            target: x86_64-pc-windows-msvc
+#          - host: ubuntu-latest
+#            target: x86_64-unknown-linux-gnu
+#            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
+#            output_suffix: linux-x64-gnu
+#            build: |-
+#              set -e &&
+#              yarn build --target x86_64-unknown-linux-gnu &&
+#              strip *.node
+#    name: stable - ${{ matrix.settings.target }} - node@18
+#    runs-on: ${{ matrix.settings.host }}
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Setup node
+#        uses: actions/setup-node@v3
+#        if: ${{ !matrix.settings.docker }}
+#        with:
+#          node-version: 18
+#          check-latest: true
+#          cache: yarn
+#      - name: Install
+#        uses: dtolnay/rust-toolchain@stable
+#        if: ${{ !matrix.settings.docker }}
+#        with:
+#          toolchain: stable
+#          targets: ${{ matrix.settings.target }}
+#      - name: Cache cargo
+#        uses: actions/cache@v3
+#        with:
+#          path: |
+#            ~/.cargo/registry/index/
+#            ~/.cargo/registry/cache/
+#            ~/.cargo/git/db/
+#            .cargo-cache
+#            target/
+#          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
+#      - uses: goto-bus-stop/setup-zig@v2
+#        if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' }}
+#        with:
+#          version: 0.10.1
+#      - name: Setup toolchain
+#        run: ${{ matrix.settings.setup }}
+#        if: ${{ matrix.settings.setup }}
+#        shell: bash
+#      - name: Setup node x86
+#        if: matrix.settings.target == 'i686-pc-windows-msvc'
+#        run: yarn config set supportedArchitectures.cpu "ia32"
+#        shell: bash
+#      - name: Install dependencies
+#        run: yarn install
+#      - name: Setup node x86
+#        uses: actions/setup-node@v3
+#        if: matrix.settings.target == 'i686-pc-windows-msvc'
+#        with:
+#          node-version: 18
+#          check-latest: true
+#          cache: yarn
+#          architecture: x86
+#      - name: Build in docker
+#        uses: addnab/docker-run-action@v3
+#        if: ${{ matrix.settings.docker }}
+#        with:
+#          image: ${{ matrix.settings.docker }}
+#          options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build"
+#          run: ${{ matrix.settings.build }}
+#      - name: Build
+#        run: ${{ matrix.settings.build }}
+#        if: ${{ !matrix.settings.docker }}
+#        shell: bash
+#      - name: Artifact name
+#        run: echo "ARTIFACT_NAME=$(ls ${{ env.APP_NAME }}.*.node)" >> $GITHUB_ENV
+#        shell: bash
+#      - name: List
+#        run: ls -al
+#        shell: bash
+#      - name: Upload artifact
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: ${{ env.ARTIFACT_NAME }}
+#          path: ${{ env.APP_NAME }}.*.node
+#          if-no-files-found: error
